fixtures:
  repositories:
    archive: "https://github.com/voxpupuli/puppet-archive"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    docker: "https://github.com/garethr/garethr-docker"
  symlinks:
    "prometheus": "#{source_dir}"
